export const PROCEDURES = [
  'Consultation',
  'Malaria Test',
  'Blood Test',
  'X-Ray',
  'Ultrasound',
  'COVID-19 Test',
  'Vaccination',
  'Blood Pressure Check',
  'ECG',
  'Pregnancy Test',
];

export const FACILITIES = [
  {
    id: 1,
    name: 'Lifegate Hospital',
    city: 'Lagos',
    state: 'Lagos',
    type: 'Private',
    address: '45 Lekki Road, Victoria Island',
    phone: '+2348012345678',
    distance: '0.8 km',
    official_prices: [
      { procedure: 'Consultation', price: 5000 },
      { procedure: 'Malaria Test', price: 3500 },
      { procedure: 'Blood Test', price: 8000 },
    ],
  },
  {
    id: 2,
    name: 'State Teaching Hospital',
    city: 'Lagos',
    state: 'Lagos',
    type: 'Public',
    address: 'Idi-Araba, Lagos',
    phone: '+2348023456789',
    distance: '2.3 km',
    official_prices: [
      { procedure: 'Consultation', price: 2000 },
      { procedure: 'Malaria Test', price: 1500 },
      { procedure: 'X-Ray', price: 3000 },
    ],
  },
  {
    id: 3,
    name: 'Unity Medical Center',
    city: 'Lagos',
    state: 'Lagos',
    type: 'Private',
    address: '12 Allen Avenue, Ikeja',
    phone: '+2348034567890',
    distance: '1.5 km',
    official_prices: [
      { procedure: 'Consultation', price: 4500 },
      { procedure: 'Blood Test', price: 7000 },
      { procedure: 'Ultrasound', price: 6000 },
    ],
  },
  {
    id: 4,
    name: 'Ilupeju Health Center',
    city: 'Lagos',
    state: 'Lagos',
    type: 'Public',
    address: 'Ilupeju, Lagos',
    phone: '+2348045678901',
    distance: '3.2 km',
    official_prices: [
      { procedure: 'Consultation', price: 1500 },
      { procedure: 'Vaccination', price: 2000 },
      { procedure: 'ECG', price: 2500 },
    ],
  },
  {
    id: 5,
    name: 'Premier Diagnostic Center',
    city: 'Lagos',
    state: 'Lagos',
    type: 'Private',
    address: 'Gbagada, Lagos',
    phone: '+2348056789012',
    distance: '2.1 km',
    official_prices: [
      { procedure: 'Malaria Test', price: 4000 },
      { procedure: 'Blood Test', price: 9000 },
      { procedure: 'COVID-19 Test', price: 5000 },
    ],
  },
];

export const LAGOS_LGAS = [
  'Alimosho',
  'Amuwo-Odofin',
  'Apapa',
  'Badagry',
  'Epe',
  'Gbagada',
  'Ibeju-Lekki',
  'Ifako-Ijaiye',
  'Ikorodu',
  'Ikeja',
  'Ikoyi',
  'Isolo',
  'Lekki',
  'Lagos Island',
  'Mushin',
  'Ojodu',
  'Shomolu',
  'Surulere',
  'Victoria Island',
];

export const MOCK_USER = {
  id: 1,
  first_name: 'Chioma',
  last_name: 'Okonkwo',
  email: 'chioma@example.com',
  phone: '+2349012345678',
};
